{
  super.handleIQError(iq);
  try {
    handleIQ(iq);
  }
 catch (  Exception e) {
    logd("An error occurred while trying to handle error IQ.");
    loge(e);
  }
}
