def test_Cycle(self):
    'Test that an exception is thrown on a cyclic graph.'
    graph = {'a': ['b'], 'b': ['c'], 'c': ['d'], 'd': ['a'], }

    def GetEdge(node):
        return tuple(graph[node])
    self.assertRaises(gyp.common.CycleError, gyp.common.TopologicallySorted, graph.keys(), GetEdge)
